services:
  - type: pserv
    name: db
    env: postgres
    postgres:
      version: 16
    disk:
      name: pg_data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend.Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url
