# This block defines the managed PostgreSQL database.
# It is separate from the 'services' block.
databases:
  - name: db
    plan: free # Use Render's free tier for the database
    postgres:
      version: 16

# This block defines the web services (your containers).
services:
  - type: web
    name: backend
    plan: free # Use Render's free tier for the web service
    env: docker
    dockerfilePath: ./backend.Dockerfile
    envVars:
      # This correctly links the backend to the database created above.
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      # You will still need to add this secret key in the Render dashboard.
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: frontend
    plan: free # Use Render's free tier for the web service
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    envVars:
      # This correctly links the frontend to the backend service.
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url
