# This block defines the managed PostgreSQL database.
databases:
  - name: db
    plan: free

# This block defines your web services.
services:
  - type: web
    name: backend
    plan: free
    env: docker
    dockerfilePath: ./backend.Dockerfile
    envVars:
      # This links the backend to the database defined above.
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      # You must add this secret in the Render dashboard.
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: frontend
    plan: free
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    envVars:
      # Set the backend URL using Render's internal service discovery.
      # The service name 'backend' is automatically resolved to the internal IP.
      - key: BACKEND_URL
        value: http://backend:8000