apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi92ZWN0b3JkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-key-secret
type: Opaque
data:
  gemini-api-key: QUl6YVN5QWw0V0EwYmxJS1RLTUtENTYyWERQWi1uaEQ1MW44bVRldmc=
